name: BoatRace
main: fr.doodz.boatrace.BoatRace
version: '${version}'
api-version: '1.21'
authors: [Doodz]
commands:
  boatrace:
    aliases: [br]
    description: Commandes du plugin BoatRace
    usage: /<command> help